const experiencedData = [
  {
    id: 1,
    view: '100',
    title: 'تجربه در ماسال گیلان',
    description: 'زیبا بود.',
    userName: 'Afshin',
    userImgSrc: 'https://randomuser.me/api/portraits/men/51.jpg',
    imgSrc: 'https://www.jabama.com/mag/wp-content/uploads/2020/03/where-is-masal04.jpg',
    rate: 4.5,
  },
  {
    id: 2,
    view: '24',
    title: 'هتل عباسی اصفهان',
    description: 'خیلی حال داد.',
    userName: 'Morteza',
    userImgSrc: 'https://randomuser.me/api/portraits/men/31.jpg',
    imgSrc: 'https://media.khabaronline.ir/d/2020/02/05/0/5339203.jpeg',
    rate: 5,
  },
  {
    id: 3,
    view: '1302',
    title: 'حافظیه شیراز',
    description: 'قشنگترین جای دنیا اینجاست.',
    userName: 'Mohammad',
    userImgSrc: 'https://randomuser.me/api/portraits/men/43.jpg',
    imgSrc: 'https://panel.safaraneh.com/wp-content/uploads/2022/01/hafez-000_new.jpg',
    rate: 4,
  },
  {
    id: 4,
    view: '78',
    title: 'پل خواجو اصفهان',
    description: 'شگفت‌انگیزه واقعا',
    userName: 'Ghazal',
    userImgSrc: 'https://randomuser.me/api/portraits/women/65.jpg',
    imgSrc: 'https://images.kojaro.com/2020/9/6fdc7cb3-992f-49d4-9bfe-0058dc332f97.jpg',
    rate: 4.5,
  },
  {
    id: 5,
    view: '480',
    title: 'ساحل سرخ جزیره هرمز',
    description: 'بسیار دلنشین و لذت‌بخش',
    userName: 'Bayan',
    userImgSrc: 'https://randomuser.me/api/portraits/women/13.jpg',
    imgSrc: 'https://images.kojaro.com/2021/10/ed442378-76fd-4500-b348-c0743eaa1068.jpg',
    rate: 5,
  },
  {
    id: 6,
    view: '276',
    title: 'غار علیصدر همدان',
    description: 'وای به این همه زیبایی!',
    userName: 'Danial',
    userImgSrc: 'https://randomuser.me/api/portraits/men/3.jpg',
    imgSrc: 'https://www.alibaba.ir/mag/wp-content/uploads/2020/03/0-850%C3%97440-Alisadr-Cave.jpg',
    rate: 4,
  },
  {
    id: 7,
    view: '1853',
    title: 'باغ موزه مقدم تهران',
    description: 'عالی بود.',
    userName: 'Hanie',
    userImgSrc: 'https://randomuser.me/api/portraits/women/81.jpg',
    imgSrc: 'https://www.ghoghnos.net/blog/wp-content/uploads/2020/01/00-1-1024x675.jpg',
    rate: 4.5,
  },
  {
    id: 8,
    view: '369',
    title: 'باداب سورت مازندران',
    description: 'واقعا بی‌نظیر هستش. تا حالا جای به این قشنگی ندیده بودم.',
    userName: 'Emad',
    userImgSrc: 'https://randomuser.me/api/portraits/men/44.jpg',
    imgSrc: 'https://www.irannegintravel.com/uploads/Highlights/Badabe%20surt/Badabe%20surt1.jpg',
    rate: 5,
  },
];
export default experiencedData;
